language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t elhotiby1/docker-test .

script:
  - docker run -e CI=true elhotiby1/docker-test yarn test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-test3'
  env: 'DockerTest3-env'
  bucket_name: 'elasticbeanstalk-us-east-1-155684741557'
  bucket_path: 'docker-test3'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
